### ISSUE TITLE
zlib not found when running KAT (although found when compiling KAT)

### ISSUE THREAD

**Issue by jflot** [TGAC/KAT#110]
Hello,
I installed KAT without apparent problem. zlib1.2.11 is present and detected by the configure script:
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes

However, when running KAT in compare mode I get an error message informing me that zlib is not found:
Creating plot(s) ...Traceback (most recent call last):
  File "//home/share/kat/scripts/kat/plot/spectra_cn.py", line 3, in <module>
    import argparse
zipimport.ZipImportError: can't decompress data; zlib not available

I tried to add an "import zlib" on line 3 of the spectra_cn.py script (just to see the result) and here is what I get:
Creating plot(s) ...Traceback (most recent call last):
  File "//home/ucbtlot/share/kat/scripts/kat/plot/spectra_cn.py", line 3, in <module>
    import zlib
ImportError: /share/python-3.5.1/lib/python3.5/lib-dynload/zlib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyExc_MemoryError

I have both Python2.7 and Python3.5 installed on my system, could it be the reason for the problem?

Thanks a lot in advance for your help.

**Comment by jflot** [comment]
I forgot to mention that if I start any of the python versions on my system and type "import zlib" and/or "import argparse", it works well without producing any error message... So I am really at a loss here.
