### ISSUE TITLE
kat comp fails during plotting

### ISSUE THREAD

**Issue by unode** [TGAC/KAT#117]
With kat from bioconda:
```
% kat --version
kat 2.4.1
```
There's `2.4.2` but not yet on bioconda. Made a pull request [here](https://github.com/bioconda/bioconda-recipes/pull/11976)
Is this by any chance fixed on the newer version already?

With the command:
```
kat comp -t 8 -m 45 -o k45_NT5009_NT5025 NT5009.fna NT5025.fna
```

KAT fails during plotting. See below.

**Since I'm not interested in the plots at all, is there any way to skip/disable that step?**

```
Kmer Analysis Toolkit (KAT) V2.4.1

Running KAT in COMP mode
------------------------

Input 1 is a sequence file.  Counting kmers for input 1 (NT5009.fna) ... done.  Time taken: 0.2s

Input 2 is a sequence file.  Counting kmers for input 2 (NT5025.fna) ... done.  Time taken: 0.2s

Comparing hashes ... done.  Time taken: 0.9s

Merging results ... done.  Time taken: 0.8s

Saving results to disk ... done.  Time taken: 0.2s


Summary statistics
------------------

K-mer statistics for: 
 - Hash 1: "NT5009.fna"
 - Hash 2: "NT5025.fna"

Total K-mers in: 
 - Hash 1: 3255070
 - Hash 2: 2174411

Distinct K-mers in:
 - Hash 1: 3248462
 - Hash 2: 2122950

Total K-mers only found in:
 - Hash 1: 3255021
 - Hash 2: 2174166

Distinct K-mers only found in:
 - Hash 1: 3248413
 - Hash 2: 2122901

Shared K-mers:
 - Total shared found in hash 1: 49
 - Total shared found in hash 2: 245
 - Distinct shared K-mers: 49

Distance between spectra 1 and 2 (all k-mers):
 - Manhattan distance: 1.16728e+06
 - Euclidean distance: 1.14646e+06
 - Cosine distance: 2.24895e-05
 - Canberra distance: 5.4236
 - Jaccard distance: 0.357038

Distance between spectra 1 and 2 (shared k-mers):
 - Manhattan distance: 98
 - Euclidean distance: 69.2965
 - Cosine distance: 1
 - Canberra distance: 2
 - Jaccard distance: 1

Creating plot(s) ...Traceback (most recent call last):
  File "/share/miniconda3/envs/apps/lib/python3.5/local/kat/plot/spectra_cn.py", line 227, in <module>
    main()
  File "/shareminiconda3/envs/apps/lib/python3.5/local/kat/plot/spectra_cn.py", line 170, in main
    ymax = np.max(peaky) * 1.1
  File "/share/miniconda3/envs/apps/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/share/miniconda3/envs/apps/lib/python3.5/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
  Time taken: 2.1s

KAT COMP completed.
Total runtime: 4.5s

../lib/include/kat/pyhelper.hpp(159): Throw in function void kat::PyHelper::execute(std::string, int, char**)
Dynamic exception type: boost::exception_detail::clone_impl<kat::KatPythonException>
std::exception::what: std::exception
[kat::KatPythonError*] = Unexpected python error
```

**Comment by maplesond** [comment]
I think the latest version does fix this.  I tried updating bioconda with the latest version a while back but run into some difficulties that occured due to changes in their build system.  When I get some time I'll try to chase that up.  In the meantime I'd recommend installing from source, or use the docker or singularity containers that are on docker hub / singularity hub respectively.
