### ISSUE TITLE
Using KAT to generate the k-mer spectrum

### ISSUE THREAD

**Issue by Otis-chan** [TGAC/KAT#153]
Hi,
I have a questions about using the KAT to generate k-mer spectrum from the fastq data. The command is `kat hist fq1 fq2 -t 16 -m 21 -o prefix`.

And I just want to get the spectrum for further analysis, but the error poped out which is :

`ERROR`

`Traceback (most recent call last):`
  
`File "/home/chphl/biosoft/miniconda3/envs/KAT/lib/python3.6/local/kat/distanalysis.py", line 440, in main`
`    a.plot(xmax=args.freq_cutoff, to_screen=args.plot, file_prefix=args.output_prefix)`

`File "/home/chphl/biosoft/miniconda3/envs/KAT/lib/python3.6/local/kat/distanalysis.py", line 67, in plot`
`    if len(self.spectra.peaks) == 0:`
`TypeError: object of type 'NoneType' has no len()`
but I check the script `distanalysis.py`, I think it told about some errors in the k-mer plotting process. I am not sure whether I'm right or not and whether it could affect the k-mer generation process. I'll really appreciate it, if you could give me a hint.

**Comment by jonwright99** [comment]
Can you tell me which version of KAT you are using? I'm running 2.1.1 and the following command works for me;

kat hist -o prefix -t 16 -m 21 reads_R?.fastq

Maybe try putting the FASTQ files as the final argument.

**Comment by bjclavijo** [comment]
closing due to inactivity
