### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by xiekunwhy** [TGAC/KAT#178]
Hi,

when running v2.4.2 (bioconda), I got following errors, do you know why?

/Bio/User/kxie/software/mambaforge/envs/kat/bin/kat gcp -o kat.gcp -t 10 -m 21 -p pdf Aeu.count.jf
ERROR
\-----
Traceback (most recent call last):
  File "//Bio/User/kxie/software/mambaforge/envs/kat/share/kat/scripts/kat/distanalysis.py", line 440, in main
    a.plot(xmax=args.freq_cutoff, to_screen=args.plot, file_prefix=args.output_prefix)
  File "//Bio/User/kxie/software/mambaforge/envs/kat/share/kat/scripts/kat/distanalysis.py", line 132, in plot
    if len(self.cov_spectra.peaks) == 0:
TypeError: object of type 'NoneType' has no len()
Error: signal 11:
Stack trace:
/Bio/User/kxie/software/mambaforge/envs/kat/bin/kat(+0x8388c)[0x2aca2152f88c]
/Bio/lib64/libc.so.6(+0x32660)[0x2aca220a0660]
/Bio/lib64/libc.so.6(+0x790fd)[0x2aca220e70fd]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(PyObject_Free+0x196)[0x2aca21b42e46]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(+0x1da900)[0x2aca21bff900]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(+0x1b6869)[0x2aca21bdb869]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(+0x1da707)[0x2aca21bff707]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(+0x123538)[0x2aca21b48538]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(_PyGC_CollectNoFail+0x3e)[0x2aca21c0c77e]
/Bio/User/kxie/software/mambaforge/envs/kat/bin/../lib/libpython3.9.so.1.0(Py_FinalizeEx+0x194)[0x2aca21c0afe4]

Best,
Kun

**Comment by praimondeau** [comment]
Hi, I run into the same error. Have you figured out what is happening?
