### ISSUE TITLE
Error with KAT_distanalysis.py

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#82]
Hi,

I'm using KAT 2.3.1 and trying to run KAT_distanalysis.py.

This is the error I get:
```
$ $TOOLS/kat/kat-2.3.1/scripts/kat_distanalysis.py kat.hist
Traceback (most recent call last):
  File "/cfs/klemming/nobackup/m/mahpa906/Tools/kat/kat-2.3.1/scripts/kat_distanalysis.py", line 413, in <module>
    a=MXKmerSpectraAnalysis(args.matrix_file, args.cns, args.freq_cutoff)
  File "/cfs/klemming/nobackup/m/mahpa906/Tools/kat/kat-2.3.1/scripts/kat_distanalysis.py", line 292, in __init__
    self.spectras.append(KmerSpectra(filename,points,column=i,cumulative=(i==columns-1)))
  File "/cfs/klemming/nobackup/m/mahpa906/Tools/kat/kat-2.3.1/scripts/kat_distanalysis.py", line 22, in __init__
    self.read_hist(histo_file,points,column,cumulative=cumulative)
  File "/cfs/klemming/nobackup/m/mahpa906/Tools/kat/kat-2.3.1/scripts/kat_distanalysis.py", line 29, in read_hist
    self.histogram=[int(x.split()[column]) for x in f.readlines() if x and x[0]!='#'][:points][1:]
  File "/cfs/klemming/nobackup/m/mahpa906/Tools/kat/kat-2.3.1/scripts/kat_distanalysis.py", line 29, in <listcomp>
    self.histogram=[int(x.split()[column]) for x in f.readlines() if x and x[0]!='#'][:points][1:]
IndexError: list index out of range
```
Am I doing something wrong? The documentation said this tool accepts a histogram file.

"To this end we bundle a script with kat called kat_distanalysis.py. It takes in either a spectra-cn matrix file, or kat histogram file as input, "

The histogram file was generated using this:
```
mkfifo alldata.fastq && zcat *.fastq.gz > alldata.fastq &
$TOOLS/kat/kat-2.3.1/src/kat hist -o kat.hist alldata.fastq 
```

Regards,
Mahesh.

**Comment by mahesh-panchal** [comment]
Sorry, I didn't realise there was a new release
