### ISSUE TITLE
Running kat_distanalysis.py in a headless environment.

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#89]
Hi,

I was trying to run kat_distanalysis.py in a headless environment and got the following error:
```
Traceback (most recent call last):
  File "/sw/apps/bioinfo/KAT/2.3.4/rackham/bin/kat_distanalysis.py", line 679, in main
    a.plot(to_screen=args.plot, to_files=args.output_prefix)
  File "/sw/apps/bioinfo/KAT/2.3.4/rackham/bin/kat_distanalysis.py", line 431, in plot
    fig = plt.figure()
  File "/sw/comp/python/3.5.0_rackham/lib/python3.5/site-packages/matplotlib-1.4.3-py3.5-linux-x86_64.egg/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/sw/comp/python/3.5.0_rackham/lib/python3.5/site-packages/matplotlib-1.4.3-py3.5-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/sw/comp/python/3.5.0_rackham/lib/python3.5/site-packages/matplotlib-1.4.3-py3.5-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/sw/comp/python/3.5.0_rackham/lib/python3.5/tkinter/__init__.py", line 1867, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:16.0"
```

I was able to fix it by adding the following lines to kat_distanalysis.py
```
import matplotlib
matplotlib.use('Agg')
```

Could something like this be added to the scripts so they can also run in headless environments please (if it doesn't cause major issues)?

**Comment by maplesond** [comment]
Hi Mahesh,
Yes, this is fine.  I'll add this in to the development branch.
Cheers,
Dan

**Comment by maplesond** [comment]
Hi Mahesh,
This issue should be addressed in the latest release.  I'll close the issue now.  If there are any problems feel free to reopen.
